"""Versioned domain contracts for OpenAlpha CN."""

from openalpha_cn.domain.decision import AgentDecision, DecisionLedger
from openalpha_cn.domain.evidence import EvidenceSnapshot
from openalpha_cn.domain.name_history import (
    NameHistory,
    NameHistoryError,
    NameHistoryHorizonError,
    NameRecord,
    RiskWarning,
    build_name_history,
    name_histories_from_panel_rows,
    risk_warning_of,
)
from openalpha_cn.domain.panel_batch import (
    ColumnarPanelBatch,
    PanelBatchError,
    PanelColumn,
    PanelColumnKind,
    TimelineColumns,
)
from openalpha_cn.domain.run import ArtifactDigest, CheckpointRecord, RunManifest, VersionRef
from openalpha_cn.domain.signal import SignalFrame
from openalpha_cn.domain.stock_universe import (
    KNOWN_UNIVERSE_LIMITATIONS,
    ListingStatus,
    SecurityLifecycle,
    StockUniverse,
    StockUniverseError,
    UniverseCompleteness,
    UniverseHorizonError,
    UniverseLimitation,
    build_stock_universe,
    listed_universe_by_trading_day,
    stock_universe_from_panel_rows,
)
from openalpha_cn.domain.time import Timeline, ensure_aware, is_visible_at
from openalpha_cn.domain.trading_calendar import (
    KNOWN_CALENDAR_LOOKAHEAD,
    CalendarDay,
    CalendarDayStatus,
    CalendarHorizon,
    CalendarHorizonError,
    CalendarLookahead,
    TradingCalendar,
    TradingCalendarError,
    build_trading_calendar,
    trading_calendar_from_panel_rows,
)
from openalpha_cn.domain.validation import AttributionTerm, ValidationResult

__all__ = [
    "KNOWN_CALENDAR_LOOKAHEAD",
    "KNOWN_UNIVERSE_LIMITATIONS",
    "AgentDecision",
    "ArtifactDigest",
    "AttributionTerm",
    "CalendarDay",
    "CalendarDayStatus",
    "CalendarHorizon",
    "CalendarHorizonError",
    "CalendarLookahead",
    "CheckpointRecord",
    "ColumnarPanelBatch",
    "DecisionLedger",
    "EvidenceSnapshot",
    "ListingStatus",
    "NameHistory",
    "NameHistoryError",
    "NameHistoryHorizonError",
    "NameRecord",
    "PanelBatchError",
    "PanelColumn",
    "PanelColumnKind",
    "RiskWarning",
    "RunManifest",
    "SecurityLifecycle",
    "SignalFrame",
    "StockUniverse",
    "StockUniverseError",
    "Timeline",
    "TimelineColumns",
    "TradingCalendar",
    "TradingCalendarError",
    "UniverseCompleteness",
    "UniverseHorizonError",
    "UniverseLimitation",
    "ValidationResult",
    "VersionRef",
    "build_name_history",
    "build_stock_universe",
    "build_trading_calendar",
    "ensure_aware",
    "is_visible_at",
    "listed_universe_by_trading_day",
    "name_histories_from_panel_rows",
    "risk_warning_of",
    "stock_universe_from_panel_rows",
    "trading_calendar_from_panel_rows",
]
